#!/usr/bin/ruby
require 'socket'
require 'openssl'
require "myname"

name_bak = "test/"

while true do
## Ask Content Name
p 'Enter content name'
print '/'
name = gets.chop

if name.nil?
  name = name_bak
else
  name_bak = name
end
puts name

ipaddr = Ipv4Name.get_ipaddr(name)
udp = UDPSocket.open()

sockaddr = Socket.pack_sockaddr_in(5002, ipaddr)
udp.send(name, 0, sockaddr)
udp.close

end
